name: deploy_multidocker
on:
  push:
    branches:  [ "master" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#      - run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
#      - run: docker run -e CI=true cygnetops/react-test npm test

      - run: docker build -t cygnetops/multi-client-10-14 ./client
      - run: docker build -t cygnetops/multi-nginx-10-14 ./nginx
      - run: docker build -t cygnetops/multi-server-10-14 ./server
      - run: docker build -t cygnetops/multi-worker-10-14 ./worker

      - run: docker push martinnovacek/multi-client-10-14
      - run: docker push martinnovacek/multi-nginx-10-14
      - run: docker push martinnovacek/multi-server-10-14
      - run: docker push martinnovacek/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-us-east-1-365950681886
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
